server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location = /flag.txt {
    if ($cookie_admin != "super_secret_admin_2026") {
      return 404;
    }
  }
}
